SocialMediaProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(),name='test'),
    path('thanks/', views.ThanksPage.as_view(),name='thanks'),
    path("posts/", include("posts.urls", namespace="posts")),
    path("groups/",include("groups.urls", namespace="groups")),
]

groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$', views.ListGroups.as_view(),name='all'),
    url(r'^new/$',views.CreateGroup.as_view(),name='create'),
    url(r'posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single'),
    url(r'join/(?P<slug>[-\w]+)/$', views.JoinGroup.as_view(),name='join'),
    url(r'leave/(?P<slug>[-\w]+)/$', views.LeaveGroup.as_view(),name='leave')
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(),name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)',views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(),name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete')
]

groups/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django.urls import reverse

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(default='', blank=True)
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})
    
    class Meta:
        ordering =['name']
    


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')
    

groups/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from . import models
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404
from groups.models import Group, GroupMember

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request, 'Warning already a member')
        else:
            messages.success(self.request, 'You are now a member')
        
        return super().get(request,*args, **kwargs)
    
class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):

        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in Group!')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group!')
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock pregroup %}
        {% block group_content %}{% endblock group_content %}
        {% block postgroup %}{% endblock postgroup %}
    </div>
</div>

{% endblock content %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}

    <h1>{{group.name}}</h1>
    <h2>Member Count: {{group.members.count}}</h2>

    <div class="content">

        {% if user in group.members.all%}
            <a href="{% url 'groups:leave' slug=group.slug %}" 
            class="btn btn-lg btn-warning">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-frown" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M4.285 12.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z"/>
            Leave</svg>
            </a>
        
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" 
            class="btn btn-lg btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-laughing" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M12.331 9.5a1 1 0 0 1 0 1A4.998 4.998 0 0 1 8 13a4.998 4.998 0 0 1-4.33-2.5A1 1 0 0 1 4.535 9h6.93a1 1 0 0 1 .866.5zM7 6.5c0 .828-.448 0-1 0s-1 .828-1 0S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 0-1 0s-1 .828-1 0S9.448 5 10 5s1 .672 1 1.5z"/>
            Join</svg>
            </a>

        {% endif %}
    </div>

{% endblock pregroup %}

{% block group_content %}

    <div class="col-md-8">
        {% if group.posts.count == 0 %}
            <h2>No posts in this group yet!</h2>
        {% else %}
            {% for post in group.posts.all %}
                {% include "posts/_post.html" %}
            {% endfor %}
        {% endif %}
    </div>



{% endblock group_content %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load crispy_forms_tags %}


{% block group_content %}

    <h4>Create a new group!</h4>

    <form method="POST" id="groupForm" action="{% url 'groups:create' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success btn-large" value="Create">Submit</button>

    </form>

{% endblock group_content %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}

    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>Welcome Back!
                    <a href={% url 'posts:for_user' username=user.username %}>
                    @{{user.username}}
                    </a>
                </h2>
            {% endif %}

            <h2>Groups</h2>
            <p>Welcome to the groups page!</p>

        </div>
        {% if user.is_authenticated %}
            <a href={% url 'groups:create' %} class="btn btn-md btn-fill btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-plus" viewBox="0 0 16 16">
                <path d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7z"/>
                <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                Create New Group!</svg>
            </a>
        {% endif %}
    </div>

{% endblock pregroup %}


{% block group_content %}

    <div class="col-md-8">
        <div class="list-group">
            {% for group in object_list %}
                <a href={% url 'groups:single' slug=group.slug %} class="list-group-item">
                    <h3 class="title list-group-item-heading">{{group.name}}</h3>
                    <div class="list-group-item-text container-fluid">
                        {{group.description_html|safe}}
                        <div class="row">
                            <div class="col-md-4">
                                <span class="badge">{{group.members.count}}</span>
                                member{{group.members.count|pluralize}}
                            </div>
                            <div class="col-md-4">
                                <span class="badge">{{group.posts.count}}</span>
                                post{{group.posts.count|pluralize}}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

{% endblock group_content %}